// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyr6mhYH5csIDKN_nGTqVNp4hTKKvrYjw',
    appId: '1:63310639375:web:c6a0916efbb4464a73ce7a',
    messagingSenderId: '63310639375',
    projectId: 'heavy-duty-app',
    authDomain: 'heavy-duty-app.firebaseapp.com',
    storageBucket: 'heavy-duty-app.appspot.com',
    measurementId: 'G-TCJJ0LNGW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmb53yqLHnK2mPE5evwpwdKsVnl0XYLwk',
    appId: '1:63310639375:android:46326d41f193c2c173ce7a',
    messagingSenderId: '63310639375',
    projectId: 'heavy-duty-app',
    storageBucket: 'heavy-duty-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhx7K2cqnhYgTm-AHUI8mQu9p3sLTQESo',
    appId: '1:63310639375:ios:f69dd977bbfbf5f073ce7a',
    messagingSenderId: '63310639375',
    projectId: 'heavy-duty-app',
    storageBucket: 'heavy-duty-app.appspot.com',
    iosBundleId: 'com.example.heavydutyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhx7K2cqnhYgTm-AHUI8mQu9p3sLTQESo',
    appId: '1:63310639375:ios:6a64630bbbf2adb773ce7a',
    messagingSenderId: '63310639375',
    projectId: 'heavy-duty-app',
    storageBucket: 'heavy-duty-app.appspot.com',
    iosBundleId: 'com.example.heavydutyapp.RunnerTests',
  );
}
